#s3_bucket_with_prefix: s3-bucket20210929163229537900000001/oracle-11g-software
s3_bucket_with_prefix: ec2-image-builder-nomis20220314103938567000000001/oracle-11g-software
artefact_dir: /u02
oracle_tar: oracle-11gR2-asmlib-v1.tar.gz
opatch: opatch_p6880880_112000_Linux-x86-64.zip

stage: "{{ artefact_dir }}/stage"
temp: "{{ artefact_dir }}/temp"
patch: "{{ stage }}/patches"
oracle_home: /u01/app/oracle/product/11.2.0.4
oracle_inventory: /u01/app/oraInventory
oracle_PATH: /usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/oracle/.local/bin:/home/oracle/bin # this is to avoid having to source oracle environment variables

database_response_file: db_install.rsp
database_base: /u01/app/oracle
database_home: "{{ oracle_home }}/db_1"

grid_response_file: grid_install.rsp
grid_base: /u01/app/grid
grid_home: "{{ oracle_home }}/gridhome_1"

password_response_file: grid_pw.rsp

asmpassword: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits length=12') }}"
asmmonitorpassword: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits length=12') }}"

grid_env:
  ORACLE_HOME: "{{ grid_home }}"
  PATH: "{{ grid_home }}/bin:{{ oracle_PATH }}"

db_env:
  ORACLE_HOME: "{{ database_home }}"
  PATH: "{{ database_home }}/bin:{{ oracle_PATH }}"

oracle_asm_data_disks: # the 'device' needs to match the device name in AWS
  - device: /dev/sde
    label: DATA01
  - device: /dev/sdf
    label: DATA02
  - device: /dev/sdg
    label: DATA03
  - device: /dev/sdh
    label: DATA04
  - device: /dev/sdi
    label: DATA05

oracle_asm_flash_disks:
  - device: /dev/sdj
    label: FLASH01
  - device: /dev/sdk
    label: FLASH02

oracle_externaljob_bin_path: /u01/app/oracle/product/11.2.0.4/db_1/bin/extjob
oracle_externaljob_rdbms_path: /u01/app/oracle/product/11.2.0.4/db_1/rdbms/admin
oracle_externaljob_file: externaljob.ora
