- name: install common packages
  ansible.builtin.yum:
    name:
      - zip
      - unzip
      - wget
      - gcc
      - screen # for AWS Session Manager logging
    state: present
    update_cache: yes
    enablerepo: rhel-7-server-rhui-extras-rpms

- name: download aws cli
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    tmp_dest: /tmp

- name: unarchive files
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes

- name: install aws cli
  ansible.builtin.command:
    cmd: /tmp/aws/install
    creates: /usr/local/bin/aws
