# there's a big assumption here that we're running on one of the newer Nitro
# based EC2 instances.  If not then this will not work in its current state.

- name: map ebs device names
  import_role:
    name: common
    tasks_from: drive_map.yml
  tags:
    - amibuild

- name: setup disks
  block:
    - import_tasks: configure_swap_disk.yml
    - import_tasks: configure_oracle_disk.yml
  tags:
    - amibuild
