# from Galaxy
roles:

collections:
  - name: community.general
    source: https://galaxy.ansible.com
    version: 3.7.0
  - name: amazon.aws
    source: https://galaxy.ansible.com
    version: 3.2.0
  - name: community.aws
    source: https://galaxy.ansible.com
    version: 3.2.1
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: 1.4.0
